import { AlertTriangle, ArrowRight, CheckCircle2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { StageBanner } from '../../components/layout/StageBanner';
import { Button } from '../../components/ui/Button';
import { Card, CardTitle } from '../../components/ui/Card';
import { KpiStat } from '../../components/ui/KpiStat';
import { PageHeader, tableClass, tdClass, thClass } from '../../components/ui/Page';
import { useAppStore } from '../../store/useAppStore';

const segments=[{name:'Electronics',wape:9.8,bias:-1.2,flag:'Healthy'},{name:'Home',wape:11.4,bias:0.8,flag:'Healthy'},{name:'Apparel',wape:14.8,bias:-4.9,flag:'Review'},{name:'Grocery',wape:8.9,bias:1.4,flag:'Healthy'},{name:'West',wape:13.2,bias:-3.7,flag:'Watch'}];
export function SegmentBiasPage(){const nav=useNavigate();const complete=useAppStore(s=>s.completeStage);const next=()=>{complete('segment-performance','experiments');nav('/experiments');};return <div><StageBanner stage="segment-performance" prerequisite="Complete training to calculate segment diagnostics."/><PageHeader eyebrow="Performance · Step 8" title="Inspect segment performance & bias" description="Find systematic under- or over-forecasting hidden by the portfolio average."/><div className="mb-5 grid gap-4 sm:grid-cols-3"><KpiStat label="Portfolio WAPE" value="10.9%" detail="Within 12% target"/><KpiStat label="Bias" value="-0.4%" detail="Within ±3% threshold"/><KpiStat label="Flagged segments" value="2" detail="Apparel and West"/></div><div className="grid gap-5 xl:grid-cols-2"><Card><CardTitle>WAPE by segment</CardTitle><div className="h-64"><ResponsiveContainer><BarChart data={segments} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis dataKey="name" type="category" width={75}/><Tooltip/><Bar dataKey="wape" fill="#6D5CE0" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></Card><Card><CardTitle>Diagnostic register</CardTitle><table className={tableClass}><thead><tr><th className={thClass}>Segment</th><th className={thClass}>WAPE</th><th className={thClass}>Bias</th><th className={thClass}>Status</th></tr></thead><tbody>{segments.map(s=><tr key={s.name}><td className={tdClass+" font-semibold"}>{s.name}</td><td className={tdClass}>{s.wape}%</td><td className={tdClass}>{s.bias}%</td><td className={tdClass}>{s.flag==='Healthy'?<span className="text-teal"><CheckCircle2 size={16}/></span>:<span className="flex gap-1 text-amber"><AlertTriangle size={16}/>{s.flag}</span>}</td></tr>)}</tbody></table></Card></div><div className="mt-5 flex justify-end"><Button onClick={next}>Review experiments<ArrowRight size={16}/></Button></div></div>}
